import { defineField, defineType } from "sanity";

export const filteredBlogPostType = defineType({
  name: "filteredBlogPost",
  title: "Filtered Blog Post",
  type: "document",
  fields: [
    defineField({
      name: "title",
      type: "string",
    }),
    defineField({
      name: "description",
      type: "string",
    }),
    defineField({
      name: "content",
      type: "blockContent",
    }),
    defineField({
      name: "filters",
      type: "object",
      fields: [
        {
          name: "task",
          type: "string",
          options: {
            list: [
              "",
              "Animal (human/non-human) imitation",
              "Audio generation",
              "Character recognition",
              "Chat",
              "Code autocompletion",
              "Code generation",
              "Face recognition",
              "Go",
              "Image captioning",
              "Image classification",
              "Image generation",
              "Language generation",
              "Language modelling",
              "Language modelling/generation",
              "Object detection",
              "Protein generation",
              "Protein or nucleotide language model (pLM/nLM)",
              "Proteins",
              "Quantitative reasoning",
              "Question answering",
              "Retrieval-augmented generation",
              "Robotic manipulation",
              "Search",
              "Self-driving car",
              "Semantic embedding",
              "Semantic search",
              "Sentiment classification",
              "Speech recognition",
              "Speech synthesis",
              "Table tasks",
              "Text autocompletion",
              "Text classification",
              "Text summarization",
              "Text summarization\n",
              "Text-to-image",
              "Translation",
              "Video description",
              "Video generation",
              "Vision-language generation",
              "Visual question answering",
            ],
          },
        },
        {
          name: "domain",
          type: "string",
          options: {
            list: [
              "",
              "Audio",
              "Biology",
              "Games",
              "Image generation",
              "Language",
              "Mathematics",
              "Multimodal",
              "Robotics",
              "Speech",
              "Video",
              "Vision",
            ],
          },
        },
        {
          name: "organization",
          type: "string",
          options: {
            list: [
              "01.AI",
              "360 Security Technology",
              "AI inside",
              "AI21 Labs",
              "Adept",
              "Adobe",
              "Aleph Alpha",
              "Alibaba",
              "Allen Institute for AI",
              "Amazon",
              "Ant Group",
              "Anthropic",
              "Apple",
              "Baichuan",
              "Baidu",
              "Beijing Academy of Artificial Intelligence / BAAI",
              "BigCode",
              "BigScience",
              "BioMap Research",
              "Bloomberg",
              "ByteDance",
              "China Mobile",
              "China Telecom",
              "Chinese University of Hong Kong (CUHK)",
              "Cohere",
              "Cohere for AI",
              "Dahua Technology",
              "Databricks",
              "DeepLang AI",
              "DeepMind",
              "DeepSeek",
              "EvolutionaryScale",
              "Facebook AI Research",
              "Fudan University",
              "Google",
              "Google Brain",
              "Google DeepMind",
              "Google Research",
              "High-Performance Language Technologies (HPLT)",
              "Hong Kong Baptist University",
              "Huawei",
              "Huawei Noah's Ark Lab",
              "Hugging Face",
              "IBM",
              "IBM Research",
              "Inflection AI",
              "Inspur",
              "JD.com",
              "Johns Hopkins University",
              "KT",
              "Konan Technology",
              "Kuaishou Technology",
              "Kunlun Inc.",
              "LG",
              "LightOn",
              "Meta AI",
              "Mianbi Intelligence",
              "Microsoft",
              "Microsoft Research",
              "Midjourney",
              "MiniMax",
              "Mistral AI",
              "MosaicML",
              "NAVER",
              "NCSOFT",
              "NEC Laboratories",
              "NTT Communication Science Laboratories",
              "NVIDIA",
              "Nanbeige LLM Lab",
              "National University of Singapore",
              "NetEase",
              "New York University (NYU)",
              "OpenAI",
              "Peking University",
              "Peng Cheng Laboratory",
              "Preferred Networks Inc",
              "Reka AI",
              "Ruhr University Bochum",
              "Runway",
              "Salesforce",
              "Samsung",
              "Saudi Aramco",
              "Sber",
              "Search Solutions",
              "SenseTime",
              "ServiceNow",
              "Shanghai AI Lab",
              "Shenzhen Yuanxiang Technology",
              "Silo AI",
              "Snowflake",
              "Stability AI",
              "TAL Education Group (Xueersi)",
              "Technion - Israel Institute of Technology",
              "Technische Universität Dresden",
              "Technology Innovation Institute",
              "Tencent",
              "Tsinghua University",
              "University of California (UC) Berkeley",
              "University of London",
              "University of Turku",
              "University of Washington",
              "XVERSE Technology",
              "Yandex",
              "Zhipu AI",
              "iFlytek",
              "vivo AI lab",
              "xAI",
            ],
          },
        },
        {
          name: "country",
          type: "string",
          options: {
            list: [
              "Canada",
              "China",
              "Finland",
              "France",
              "Germany",
              "Hong Kong",
              "Israel",
              "Japan",
              "Korea (Republic of)",
              "Multinational",
              "Russia",
              "Saudi Arabia",
              "Singapore",
              "United Arab Emirates",
              "United Kingdom of Great Britain and Northern Ireland",
              "United States of America",
            ],
          },
        },
      ],
    }),
  ],
});
